name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Install GCC, CMake, GoogleTest, cppcheck, and dependencies
    - name: Install GCC, CMake, GoogleTest, cppcheck, and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ cmake libgtest-dev build-essential cppcheck
        # Manually build GoogleTest from source (if not installed)
        cd /tmp
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake .
        sudo make install

    # Run cppcheck analysis
    - name: Run cppcheck analysis
      run: |
        cppcheck --enable=all --inconclusive --force --xml --xml-version=2 . 2> cppcheck.xml
        
    # Check for cppcheck issues
    - name: Check for cppcheck issues
      run: |
        if [ -s cppcheck.xml ]; then
          echo "Cppcheck issues found!"
          cat cppcheck.xml
          exit 1
        else
          echo "No cppcheck issues found."
        fi

    # Build the project
    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    # Run tests using Google Test
    - name: Run tests
      run: |
        cd build
        ./runTests
