name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Install GCC, CMake, GoogleTest, cppcheck, and dependencies
    - name: Install GCC, CMake, GoogleTest, cppcheck, and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ cmake build-essential cppcheck
        # Install GoogleTest from source
        cd /tmp
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake .
        sudo make install

    # Run Cppcheck for static analysis
    - name: Run static analysis with Cppcheck
      run: |
        cppcheck --enable=all --inconclusive --quiet .

    # Create the build directory and run CMake to configure the project and generate compile_commands.json
    - name: Build the project and generate compile_commands.json
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=YES .. # Optionally include other flags here
        make CXXFLAGS="-Wall -Wextra -fsanitize=address"

    # Run tests using Google Test
    - name: Run tests
      run: |
        cd build
        ./runTests
