name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up GCC
    - name: Set up GCC
      uses: actions/setup-gcc@v1
      with:
        gcc-version: 'latest'

    # Install dependencies (CMake, GoogleTest)
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        sudo apt-get install -y libgtest-dev
        sudo apt-get install -y build-essential
        # Manually build GoogleTest from source (if not installed)
        cd /tmp
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake .
        sudo make install

    # Build the project
    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    # Run tests using Google Test
    - name: Run tests
      run: |
        cd build
        ./runTests
