name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Install GCC, CMake, GoogleTest, cppcheck, and dependencies
    - name: Install GCC, CMake, GoogleTest, cppcheck, and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ cmake build-essential cppcheck
        # Install GoogleTest from source
        cd /tmp
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake .
        sudo make install

    # Create the build directory and run CMake to configure the project
    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    # Run cppcheck analysis with exclusions and include paths
    - name: Run cppcheck analysis
      run: |
        cppcheck --enable=all --inconclusive --force --xml --xml-version=2 --exclude build --std=c++17 --includes-file=/usr/include/c++/7 . 2> cppcheck.xml

    # Check for cppcheck issues
    - name: Check for cppcheck issues
      run: |
        if grep -q "<error" cppcheck.xml; then
          echo "Cppcheck issues found!"
          cat cppcheck.xml
          exit 1
        else
          echo "No cppcheck issues found."
        fi

    # Run tests using Google Test
    - name: Run tests
      run: |
        cd build
        ./runTests
