name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Install GCC, CMake, and dependencies
    - name: Install GCC, CMake, and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ cmake libgtest-dev build-essential
        # Manually build GoogleTest from source (if not installed)
        cd /tmp
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake .
        sudo make install

    # Build the project
    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    # Run tests using Google Test
    - name: Run tests
      run: |
        cd build
        ./runTests
